up:
	docker compose -f docker-compose-local.yaml up -d

down:
	docker compose -f docker-compose-local.yaml down && docker network prune -f

stop:
	docker compose -f docker-compose-local.yaml stop

restart:
	docker compose -f docker-compose-local.yaml restart

