"""Create db

Revision ID: 284392378349
Revises: 0f75d3687d0d
Create Date: 2025-04-03 18:17:52.487704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284392378349'
down_revision: Union[str, None] = '0f75d3687d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'frame_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'frame_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
