"""create user roles

Revision ID: 97a193e3e201
Revises: e39398b07aa1
Create Date: 2025-04-02 09:57:30.549823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a193e3e201'
down_revision: Union[str, None] = 'e39398b07aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = sa.Enum('ROLE_USER', 'ROLE_MODERATOR', 'ROLE_ADMIN', 'ROLE_SUPERADMIN', name='user_role')
    user_role.create(op.get_bind())
    
    # Добавляем колонку с временным значением по умолчанию
    op.add_column('users', sa.Column('roles', sa.ARRAY(user_role), nullable=True))
    
    # Обновляем существующие записи
    op.execute("UPDATE users SET roles = ARRAY['ROLE_USER']::user_role[] WHERE roles IS NULL")
    
    # Делаем колонку NOT NULL
    op.alter_column('users', 'roles', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    user_role = sa.Enum('ROLE_USER', 'ROLE_MODERATOR', 'ROLE_ADMIN', 'ROLE_SUPERADMIN', name='user_role')
    user_role.drop(op.get_bind())
    # ### end Alembic commands ###
