"""create user frame photo

Revision ID: e39398b07aa1
Revises: f64db36822be
Create Date: 2025-04-02 03:46:50.126681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39398b07aa1'
down_revision: Union[str, None] = 'f64db36822be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('frame_photo', sa.String(), nullable=True))
    op.execute("UPDATE users SET frame_photo = '/static/images/defaults/default_frame.png' WHERE frame_photo IS NULL")
    op.alter_column('users', 'frame_photo',
                    existing_type=sa.String(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frame_photo')
    # ### end Alembic commands ###
